target 'JWMTADataFeed', :exclusive => true do
  pod "JWMTADataFeed", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JWMTADataFeed", :path => "../"
  pod 'AFNetworking', '~> 2.3.1'

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
